/**
 * Static list of migration SQL files with their contents.
 * Used by both browser PGLite and test infrastructure.
 *
 * AUTO-GENERATED by pnpm codegen. Do not edit manually.
 */
import migration0000 from './0000_audit_logs.sql?raw'
import migration0001 from './0001_migration.sql?raw'
import migration0002 from './0002_agentfs.sql?raw'
import migration0003 from './0003_migration.sql?raw'
import migration0004 from './0004_migration.sql?raw'

// Migration SQL contents (in order)
export const migrations = [
  migration0000,
  migration0001,
  migration0002,
  migration0003,
  migration0004,
] as const
